### ISSUE TITLE
support issue template for bug report

### ISSUE THREAD

**Issue by yeonns** [euphony-io/euphony-collector#9]
## Description
There's no bug report issue template, so it is hard to report bug.
We need to compare other open source's issue template and apply ours.

**Comment by Chandra-Sekhar-Bala** [comment]
I would like to contribute to this project.
But as a beginner, I need some help to get started.

**Comment by designe** [comment]
@Chandra-Sekhar-Bala Actually, it is regarding with github issue template.
As you can see, this is `good first issue`.  you can suggest convinient issue templates.
if you need some help, let us know :)

**Comment by Chandra-Sekhar-Bala** [comment]
@designe @yeonns  Check this one: 

`Actual Behaviour


Expected Behaviour


Would you like to work on the issue?

`

**Comment by designe** [comment]
@Chandra-Sekhar-Bala Thanks to suggest `bug report` template.
I like last question `Would you like to work on the issue?` it's helpful for contributors ;)

I think we need to provide some examples to each questions.
For example, https://github.com/euphony-io/euphony/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

Additionaly, I'm sharing issue template references.
It's important to compare various issue templates and we can pick what we need.
- next.js : https://github.com/vercel/next.js/tree/canary/.github/ISSUE_TEMPLATE
Actually, they made it by custom issue form (YAML) 
  - custom issue form : https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
- nnstreamer : https://github.com/nnstreamer/nnstreamer/tree/main/.github/ISSUE_TEMPLATE
only markdown. and 3 options.
- oboe : https://github.com/google/oboe/blob/main/.github/ISSUE_TEMPLATE/bug_report.md
only markdown, and `bug report`
- gtest : https://github.com/google/googletest/tree/main/.github/ISSUE_TEMPLATE
they defined issue blank option.

@yeonns How about split the issue into 3 templates?
1st is for `bug report`. I think this issue is applicable for `bug report`. I think @Chandra-Sekhar-Bala can do this.
2nd is for `feature request` template.
3rd is for `docs request` template.
4th is for `question` menu ( it's good to connect to discussion page )

**Comment by yeonns** [comment]
@designe I agree with you! 
Then, this issue is only for ```bug report``` template, and can I open another issues for ```feature request``` and so on? 😄

**Comment by designe** [comment]
@yeonns exactly :) thanks!

**Comment by Chandra-Sekhar-Bala** [comment]
@designe  Yes, I would like to work on this :)

**Comment by Chandra-Sekhar-Bala** [comment]
Let's not make this complex like next.js, the one template you provided looks good i.e https://github.com/euphony-io/euphony/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
I think we can use the same here just with some modifications.
Wdyt  @designe  @yeonns ?

**Comment by designe** [comment]
@Chandra-Sekhar-Bala I agree with you.
+ some modification of euphony repo's `bug report` 
+ `what would you like to work on the issue` question 
+ custom issue form with YAML.

Above are enough. @yeonns How do you think about it?

**Comment by yeonns** [comment]
@designe Good!

@Chandra-Sekhar-Bala Would you create PR like below and link it with this issue? Then, we will review your suggestion 😄 
- Custom issue form with YAML: ```.github/ISSUE_TEMPLATE/bug-report.yaml```

**Comment by Chandra-Sekhar-Bala** [comment]
@designe @yeonns  I'm on it 🤗
